# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(539, 210)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.copy_btn = QtWidgets.QPushButton(Dialog)
        self.copy_btn.setGeometry(QtCore.QRect(190, 150, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.copy_btn.setFont(font)
        self.copy_btn.setObjectName("copy_btn")
        self.source_txt = QtWidgets.QLineEdit(Dialog)
        self.source_txt.setGeometry(QtCore.QRect(170, 30, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.source_txt.setFont(font)
        self.source_txt.setObjectName("source_txt")
        self.destination_txt = QtWidgets.QLineEdit(Dialog)
        self.destination_txt.setGeometry(QtCore.QRect(170, 70, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.destination_txt.setFont(font)
        self.destination_txt.setObjectName("destination_txt")
        self.banlist_txt = QtWidgets.QLineEdit(Dialog)
        self.banlist_txt.setGeometry(QtCore.QRect(170, 110, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.banlist_txt.setFont(font)
        self.banlist_txt.setObjectName("banlist_txt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Source Folder"))
        self.label_2.setText(_translate("Dialog", "Destination Folder"))
        self.label_3.setText(_translate("Dialog", "Ban List"))
        self.copy_btn.setText(_translate("Dialog", "Copy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
